"""
Hard-Negative Quality and Utility Analysis for Role 2.
Compares Pass A+B (High-precision exact retrieval) versus Pass A..G (Multi-pass full retrieval).
Inspects additional candidates retrieved by passes C-G, measuring string and address similarities
to determine whether they provide realistic training discriminators for Person 3's ML classifier.
"""

import sys
import os
import random
import numpy as np
import pandas as pd
from rapidfuzz import fuzz

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from benchmark_harness import generate_synthetic_benchmark
from search_engine import MultiPassSearchEngine

def analyze_hard_negatives_quality():
    print("=" * 65)
    print("TASK 11: HARD-NEGATIVE QUALITY ANALYSIS (A+B vs A..G)")
    print("=" * 65)

    s1_recs, s2s3_recs, gt = generate_synthetic_benchmark(n_s1=2000, singleton_rate=0.35, random_seed=42)
    s2s3_lookup = {r['entity_id']: r for r in s2s3_recs}

    engine = MultiPassSearchEngine(default_top_k=80)
    for r in s2s3_recs:
        engine.add_record(r['entity_id'], r['business_name'], r['business_address'], r['country'])
    engine.finalize_index()

    # Sample 100 S1 entities
    sampled_s1_ids = random.sample(list(s1_recs.keys()), 100)

    ab_candidate_counts = []
    full_candidate_counts = []
    hard_neg_similarities = []
    concrete_examples = []

    for s1_id in sampled_s1_ids:
        s1 = s1_recs[s1_id]
        gt_matches = gt.get(s1_id, set())

        # Candidates from Pass A+B only
        cands_ab = engine.retrieve(s1, top_k=80, active_passes={'exact_name', 'exact_addr'})
        ids_ab = {cid for cid, _ in cands_ab}
        ab_candidate_counts.append(len(ids_ab))

        # Candidates from Full Multi-Pass A..G
        cands_full = engine.retrieve(s1, top_k=80)
        ids_full = {cid for cid, _ in cands_full}
        full_candidate_counts.append(len(ids_full))

        # Additional candidates generated by passes C-G
        additional_ids = ids_full - ids_ab

        for aid in additional_ids:
            # Check if it's a negative (not in ground truth)
            if aid not in gt_matches:
                cand = s2s3_lookup.get(aid, {})
                c_name = cand.get('business_name', '')
                c_addr = cand.get('business_address', '')

                name_sim = fuzz.token_sort_ratio(s1['business_name'], c_name)
                addr_sim = fuzz.token_sort_ratio(s1['business_address'], c_addr)

                hard_neg_similarities.append({
                    'name_sim': name_sim,
                    'addr_sim': addr_sim,
                    'is_high_quality_hard_neg': (name_sim >= 60 or addr_sim >= 60)
                })

                if len(concrete_examples) < 5 and name_sim >= 65:
                    concrete_examples.append({
                        's1_name': s1['business_name'],
                        'cand_name': c_name,
                        'name_sim': name_sim,
                        's1_addr': s1['business_address'],
                        'cand_addr': c_addr,
                        'addr_sim': addr_sim
                    })

    df_sim = pd.DataFrame(hard_neg_similarities)
    avg_name_sim = df_sim['name_sim'].mean()
    avg_addr_sim = df_sim['addr_sim'].mean()
    pct_plausible_hard_negs = 100.0 * df_sim['is_high_quality_hard_neg'].mean()

    print(f"Candidate Volume Comparison (Sample of 100 S1 Entities):")
    print(f"  Pass A+B Average Candidates:         {np.mean(ab_candidate_counts):.2f}")
    print(f"  Pass A..G Average Candidates:        {np.mean(full_candidate_counts):.2f}")
    print(f"  Additional Candidates from C-G:      +{np.mean(full_candidate_counts) - np.mean(ab_candidate_counts):.2f} per entity")

    print(f"\nHard-Negative Quality Metrics:")
    print(f"  Average Name RapidFuzz Token Sort:   {avg_name_sim:.1f} / 100")
    print(f"  Average Address Token Sort:          {avg_addr_sim:.1f} / 100")
    print(f"  Plausible Hard Negatives (Sim >= 60): {pct_plausible_hard_negs:.1f}%")

    print(f"\nConcrete Hard-Negative Examples (Supplied to Downstream Classifier):")
    for i, ex in enumerate(concrete_examples, 1):
        print(f"\n  [Example {i}]")
        print(f"    S1 Entity:    '{ex['s1_name']}' at '{ex['s1_addr']}'")
        print(f"    Hard Neg:     '{ex['cand_name']}' at '{ex['cand_addr']}'")
        print(f"    Similarity:   Name Sim = {ex['name_sim']}%, Addr Sim = {ex['addr_sim']}%")

    return df_sim

if __name__ == '__main__':
    analyze_hard_negatives_quality()
